const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  pickFolder:       ()            => ipcRenderer.invoke('pick-folder'),
  listImages:       (f)           => ipcRenderer.invoke('list-images', f),
  ensureFolders:    (r,m)         => ipcRenderer.invoke('ensure-folders', r, m),
  moveAndRename:    (s,d,p)       => ipcRenderer.invoke('move-and-rename', s, d, p),
  undoMove:         ()            => ipcRenderer.invoke('undo-move'),
  undoMany:         (c)           => ipcRenderer.invoke('undo-many', c),
  findDuplicates:   (f)           => ipcRenderer.invoke('find-duplicates', f),
  loadPresets:      ()            => ipcRenderer.invoke('load-presets'),
  savePresets:      (p)           => ipcRenderer.invoke('save-presets', p),
  loadRatings:      (f)           => ipcRenderer.invoke('load-ratings', f),
  saveRatings:      (f,d)         => ipcRenderer.invoke('save-ratings', f, d),
  getExif:          (p)           => ipcRenderer.invoke('get-exif', p),
  checkFileExists:  (p)           => ipcRenderer.invoke('check-file-exists', p),
  setFullscreen:    (flag)        => ipcRenderer.invoke('set-fullscreen', flag),
  getFileStats:     (p)           => ipcRenderer.invoke('get-file-stats', p),
  exportLog:        (l,f)         => ipcRenderer.invoke('export-log', l, f),
  getRawPreview:    (p)           => ipcRenderer.invoke('get-raw-preview', p),
  isRawCached:      (p)           => ipcRenderer.invoke('is-raw-cached', p),
  startPreload:     (files)       => ipcRenderer.invoke('start-preload', files),
  cancelPreload:    ()            => ipcRenderer.invoke('cancel-preload'),
  onPreviewReady:   (cb)          => ipcRenderer.on('raw-preview-ready', (_,fp) => cb(fp)),
  offPreviewReady:  ()            => ipcRenderer.removeAllListeners('raw-preview-ready'),
});
